### ISSUE TITLE
analytics

### ISSUE THREAD

**Issue by ryanfiller** [tidymemphis/tidymemphis#4]
I imagine this site is going to need to get up and running pretty quick, and I think a tool to see where people have the most need would be helpful.
I reccomend something something free, opensource, and ethical like [goatcounter](https://www.goatcounter.com/). It also can be opened up to be viewed by anyone so contributors to this site could see areas of higher need - ex "lots of mobile traffic to X page and it could be optimized for mobile better."

**Comment by tidymemphis** [comment]
okay so I already have google analytics (no ad tracking) because it was the only way I knew to track page count. I want to switch to goatcounter, but I'd like to go ahead and share analytics I already have however you think is best.

**Comment by tidymemphis** [comment]
I signed up for GoatCounter, this just needs to be added in the right place:

```
<script data-goatcounter="https://tidymemphis.goatcounter.com/count"
        async src="//gc.zgo.at/count.js"></script>
```

**Comment by ryanfiller** [comment]
Hmm, I'm not really sure how to move analytics over. You might have to go in and flip a setting, but the reason I suggest goatcounter is that you can visit the url tidymemphis.goatcounter.com and have publicly facing analytics that might be helpful for others.

**Comment by tidymemphis** [comment]
Okay so looks like I can't easily share google analytics. If you give me your email I can add you so you can view the data. Otherwise, I want to switch to GoatCounter but Gatsby had a google analytics component and I'm not sure if there's something similar for Goat Counter

**Comment by ryanfiller** [comment]
I'm addressing this in [this PR](https://github.com/tidymemphis/tidymemphis/pull/6) so I'm going to go ahead and close this issue for now.
